# this is only an EXAMPLE of deploying casddor in kubernetes
# please modify this file according to your requirements
apiVersion: v1
kind: Service
metadata:
  #EDIT IT: if you don't want to run casdoor in default namespace, please modify this field
  #namespace: casdoor
  name: casdoor-svc
  labels:
    app: casdoor
spec:
  #EDIT IT: if you don't want to run casdoor in default namespace, please modify this filed
  type: NodePort
  ports:
    - port: 8000
  selector:
    app: casdoor
---
apiVersion: apps/v1
kind: Deployment
metadata:
  #EDIT IT: if you don't want to run casdoor in default namespace, please modify this field
  #namespace: casdoor
  name: casdoor-deployment
  labels:
    app: casdoor
spec:
  #EDIT IT: if you don't use redis, casdoor should not have multiple replicas
  replicas: 1
  selector:
    matchLabels:
      app: casdoor
  template:
    metadata:
      labels:
        app: casdoor
    spec:
      containers:
        - name: casdoor-container
          image: registry.cn-hangzhou.aliyuncs.com/pai-platform/casdoor:20220629-v1.62.0-2-gb7efbf-dirty
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          resources:
            limits:
              cpu: 500m
              memory: 200M
          env:
            - name: RUNNING_IN_DOCKER
              value: 'false'
            - name: appname
              value: casdoor
            - name: httpport
              value: '8000'
            - name: runmode
              value: dev
            - name: SessionOn
              value: 'true'
            - name: copyrequestbody
              value: 'true'
            - name: driverName
              value: mysql
            - name: dataSourceName
              value: 'casdoor:UO7tD8rKf11Z@tcp(rm-bp13bojp0sh66osf4.mysql.rds.aliyuncs.com:3306)/'
            - name: dbName
              value: casdoor
            - name: showSql
              value: 'true'
        - name: mysql
          image: mysql:latest
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 500m
              memory: 400M
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: '123456'
        - name: 